import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body className={`${outfit.className} relative min-h-screen w-screen`}>
      <Providers>
        <main className="w-screen">{children}</main>
      </Providers>
    </body>
  );
}
